version: '3.8'
services:
  devcontainer:
    build: .
    image: quadhawkonboard-devcontainer
    # volumes:
    #   - ../..:/workspaces:cached      
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./onboard_ws:/home/airHawk/onboard_ws
    network_mode: host
    stdin_open: true
    tty: true
    restart: "no"    
    command: sleep infinity

