version: '3.8'
services:
  devcontainer:
    build: .
    image: quadhawkonboard-devcontainer
    # volumes:
    #   - ../..:/workspaces:cached      
    environment:
      - DISPLAY
    network_mode: "host"
    stdin_open: true
    tty: true
    restart: "no"    
    command: sleep infinity

